### ISSUE TITLE
Does not compile in Debian 10 Gnome 3.30

### ISSUE THREAD

**Issue by moscaman18** [nagisa/msi-rgb#121]
Two errors repeating

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/lib.rs:15:1
   |
15 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/lib.rs:41:1
   |
41 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
 --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:5:23
  |
5 | use core::mem::{self, MaybeUninit};
  |                       ^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2312:20
     |
2312 |     rules_storage: MaybeUninit<[(Register, RegisterRule<R>); MAX_RULES]>,
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2329:28
     |
2329 |             rules_storage: MaybeUninit::uninit(),
     |                            ^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2329:41
     |
2329 |             rules_storage: MaybeUninit::uninit(),
     |                            -------------^^^^^^
     |                            |
     |                            function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2366:60
     |
2366 |             core::slice::from_raw_parts(self.rules_storage.as_ptr() as *const _, self.rules_len)
     |                                                            ^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2374:36
     |
2374 |                 self.rules_storage.as_mut_ptr() as *mut _,
     |                                    ^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2405:50
     |
2405 |                     let ptr = self.rules_storage.as_mut_ptr() as *mut (Register, RegisterRule<R>);
     |                                                  ^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2446:42
     |
2446 |             let ptr = self.rules_storage.as_mut_ptr() as *mut (Register, RegisterRule<R>);
     |                                          ^^^^^^^^^^

error[E0599]: no method named `cast` found for type `*const u8` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:35:30
   |
35 |     let val = unsafe { &*ptr.cast() };
   |                              ^^^^

error[E0599]: no method named `cast` found for type `*const u8` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:53:52
   |
53 |     let slice = unsafe { slice::from_raw_parts(ptr.cast(), count) };
   |                                                    ^^^^

error[E0599]: no method named `cast` found for type `*const T` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:65:66
   |
65 |     unsafe { slice::from_raw_parts(slice::from_ref(val).as_ptr().cast(), size) }
   |                                                                  ^^^^

error[E0658]: use of unstable library feature 'iter_copied' (see issue #57127)
   --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:291:39
    |
291 |     list.entries(bytes.iter().take(8).copied().map(DebugByte));
    |                                       ^^^^^^

error: aborting due to 9 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `gimli`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to 5 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `object`.

To learn more, run the command again with --verbose.
nigel@mosca:~/Documents/msi-rgb$ cargo build --release
   Compiling gimli v0.21.0
   Compiling object v0.19.0
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/lib.rs:15:1
   |
15 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/lib.rs:41:1
   |
41 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
 --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:5:23
  |
5 | use core::mem::{self, MaybeUninit};
  |                       ^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2312:20
     |
2312 |     rules_storage: MaybeUninit<[(Register, RegisterRule<R>); MAX_RULES]>,
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2329:28
     |
2329 |             rules_storage: MaybeUninit::uninit(),
     |                            ^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2329:41
     |
2329 |             rules_storage: MaybeUninit::uninit(),
     |                            -------------^^^^^^
     |                            |
     |                            function or associated item not found in `core::mem::MaybeUninit<_>`

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2366:60
     |
2366 |             core::slice::from_raw_parts(self.rules_storage.as_ptr() as *const _, self.rules_len)
     |                                                            ^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2374:36
     |
2374 |                 self.rules_storage.as_mut_ptr() as *mut _,
     |                                    ^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2405:50
     |
2405 |                     let ptr = self.rules_storage.as_mut_ptr() as *mut (Register, RegisterRule<R>);
     |                                                  ^^^^^^^^^^

error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
    --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.21.0/src/read/cfi.rs:2446:42
     |
2446 |             let ptr = self.rules_storage.as_mut_ptr() as *mut (Register, RegisterRule<R>);
     |                                          ^^^^^^^^^^

error[E0599]: no method named `cast` found for type `*const u8` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:35:30
   |
35 |     let val = unsafe { &*ptr.cast() };
   |                              ^^^^

error[E0599]: no method named `cast` found for type `*const u8` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:53:52
   |
53 |     let slice = unsafe { slice::from_raw_parts(ptr.cast(), count) };
   |                                                    ^^^^

error[E0599]: no method named `cast` found for type `*const T` in the current scope
  --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:65:66
   |
65 |     unsafe { slice::from_raw_parts(slice::from_ref(val).as_ptr().cast(), size) }
   |                                                                  ^^^^

error[E0658]: use of unstable library feature 'iter_copied' (see issue #57127)
   --> /home/nigel/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.19.0/src/pod.rs:291:39
    |
291 |     list.entries(bytes.iter().take(8).copied().map(DebugByte));
    |                                       ^^^^^^

error: aborting due to 9 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `gimli`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to 5 previous errors

Some errors occurred: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `object`.

To learn more, run the command again with --verbose.

**Comment by nagisa** [comment]
Use a more recent version of the compiler.

**Comment by beinvisible** [comment]
Which version of rustc should work? 

Tried with 1.41.1 (debian buster) and 1.48.0 (debian testing) - same error.

**Comment by nagisa** [comment]
Builds with 1.42 here.
